PortalForRetiredExperienced/Controllers/CandidateListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PortalForRetiredExperienced.Data.DbContexts;
using PortalForRetiredExperienced.Models;

namespace PortalForRetiredExperienced.Controllers
{
    public class CandidateListController : Controller
    {
        private readonly FrameworkDbContext _context;

        public CandidateListController(FrameworkDbContext context)
        {
            _context = context;
        }

        // GET: CandidateList
        public async Task<IActionResult> Index()
        {
            return View(await _context.CandidateList.ToListAsync());
        }
        public async Task<IActionResult> CandidateList()
        {
            return View(await _context.CandidateList.ToListAsync());
        }

        // GET: CandidateList/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var candidateListModel = await _context.CandidateList
                .FirstOrDefaultAsync(m => m.Ca_id == id);
            if (candidateListModel == null)
            {
                return NotFound();
            }

            return View(candidateListModel);
        }

        // GET: CandidateList/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CandidateList/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Ca_id,CandidateName,Profession,ProfileLink")] CandidateListModel candidateListModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(candidateListModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(candidateListModel);
        }

        // GET: CandidateList/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var candidateListModel = await _context.CandidateList.FindAsync(id);
            if (candidateListModel == null)
            {
                return NotFound();
            }
            return View(candidateListModel);
        }

        // POST: CandidateList/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Ca_id,CandidateName,Profession,ProfileLink")] CandidateListModel candidateListModel)
        {
            if (id != candidateListModel.Ca_id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(candidateListModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CandidateListModelExists(candidateListModel.Ca_id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(candidateListModel);
        }

        // GET: CandidateList/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var candidateListModel = await _context.CandidateList
                .FirstOrDefaultAsync(m => m.Ca_id == id);
            if (candidateListModel == null)
            {
                return NotFound();
            }

            return View(candidateListModel);
        }

        // POST: CandidateList/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var candidateListModel = await _context.CandidateList.FindAsync(id);
            _context.CandidateList.Remove(candidateListModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CandidateListModelExists(int id)
        {
            return _context.CandidateList.Any(e => e.Ca_id == id);
        }
    }
}

PortalForRetiredExperienced/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PortalForRetiredExperienced.Data.DbContexts;

namespace PortalForRetiredExperienced.Controllers
{
    public class CompanyController : Controller
    {
        private readonly FrameworkDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public CompanyController(FrameworkDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _webHostEnvironment = hostEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.CompanyList.ToListAsync());
        }
        public async Task<IActionResult> CompanyList()
        {
            return View(await _context.CompanyList.ToListAsync());
        }
    }
}

PortalForRetiredExperienced/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PortalForRetiredExperienced.Data.DbContexts;
using PortalForRetiredExperienced.Models;

namespace PortalForRetiredExperienced.Controllers
{
    public class ContactsController : Controller
    {
        private readonly FrameworkDbContext _context;

        public ContactsController(FrameworkDbContext context)
        {
            _context = context;
        }

        // GET: Contacts
        public async Task<IActionResult> Index()
        {
            return View(await _context.Contact.ToListAsync());
        }
        public async Task<IActionResult> Contact()
        {
            return View(await _context.Contact.ToListAsync());
        }
        
        // GET: Contacts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contact = await _context.Contact
                .FirstOrDefaultAsync(m => m.Id == id);
            if (contact == null)
            {
                return NotFound();
            }

            return View(contact);
        }

        // GET: Contacts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Contacts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FullName,Email,Phone,Subject,Message")] Contact contact)
        {
            if (ModelState.IsValid)
            {
                _context.Add(contact);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(contact);
        }

        // GET: Contacts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contact = await _context.Contact.FindAsync(id);
            if (contact == null)
            {
                return NotFound();
            }
            return View(contact);
        }

        // POST: Contacts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,Email,Phone,Subject,Message")] Contact contact)
        {
            if (id != contact.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contact);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContactExists(contact.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(contact);
        }

        // GET: Contacts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contact = await _context.Contact
                .FirstOrDefaultAsync(m => m.Id == id);
            if (contact == null)
            {
                return NotFound();
            }

            return View(contact);
        }

        // POST: Contacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contact = await _context.Contact.FindAsync(id);
            _context.Contact.Remove(contact);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContactExists(int id)
        {
            return _context.Contact.Any(e => e.Id == id);
        }
    }
}

PortalForRetiredExperienced/Controllers/ProfilesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PortalForRetiredExperienced.Areas.Admin.Models;
using PortalForRetiredExperienced.Data.DbContexts;
using PortalForRetiredExperienced.Models;

namespace PortalForRetiredExperienced.Controllers
{
    [Authorize]
    public class ProfilesController : Controller
    {
        private readonly FrameworkDbContext _context;
        private readonly ApplicationDbContext _memberShipContext;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly UserManager<IdentityUser> _userManager;

        public ProfilesController(FrameworkDbContext context , ApplicationDbContext applicationDbContext, UserManager<IdentityUser> userManager, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _memberShipContext = applicationDbContext;
            _webHostEnvironment = webHostEnvironment;
            _userManager = userManager;
        }

        // GET: Profiles
        public async Task<IActionResult>Index()
        {
            var currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier); // will give the user's userId

            return View(await _context.Profile.Where(x => x.UserId == currentUserId.ToString()).ToListAsync());
        }
        public async Task<IActionResult>Profile()
        {
            return View(await _context.Profile.ToListAsync());
        }

        // GET: Profiles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var profile = await _context.Profile
                .FirstOrDefaultAsync(m => m.P_Id == id);
            if (profile == null)
            {
                return NotFound();
            }

            return View(profile);
        }

        // GET: Profiles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Profiles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProfileCreateModel profile)
        {
            var currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier); // will give the user's userId
            var userName = User.FindFirstValue(ClaimTypes.Name);


            if (ModelState.IsValid)
            {
                string uniqueFileName = UploadedFile(profile);
                var profileEntity = new Profile
                {
                    ProfilePic = uniqueFileName,
                    JobTitle = profile.JobTitle,
                    Address = profile.Address,
                    PhoneNumber = profile.PhoneNumber,
                    DateofBirth = profile.DateofBirth,
                    UploadCv = profile.UploadCV,
                    UserId = currentUserId.ToString()
                };
                _context.Add(profileEntity);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(profile);
        }

        // GET: Profiles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var profile = await _context.Profile.FindAsync(id);
            if (profile == null)
            {
                return NotFound();
            }
            return View(profile);
        }

        // POST: Profiles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("P_Id,ProfilePic,UploadCv,DateofBirth,PhoneNumber,Address,JobTitle")] Profile profile)
        {
            if (id != profile.P_Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(profile);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProfileExists(profile.P_Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(profile);
        }

        // GET: Profiles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var profile = await _context.Profile
                .FirstOrDefaultAsync(m => m.P_Id == id);
            if (profile == null)
            {
                return NotFound();
            }

            return View(profile);
        }

        // POST: Profiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var profile = await _context.Profile.FindAsync(id);
            _context.Profile.Remove(profile);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        private string UploadedFile(ProfileCreateModel model)
        {
            string uniqueFileName = null;

            if (model.ImageFile != null)
            {
                string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.ImageFile.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.ImageFile.CopyTo(fileStream);
                } 
            }
            return uniqueFileName;
        }

        private bool ProfileExists(int id)
        {
            return _context.Profile.Any(e => e.P_Id == id);
        }
    }
}

PortalForRetiredExperienced/Views/Shared/CandidateDetails.cshtml
 <!-- Candidate Details -->
<div class="single-profile-area pt-100">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-5">
                <div class="single-profile-item">
                    <img src="assets/img/single-profile/2.jpg" alt="Profile">
                    <div class="single-profile-left">
                        <div class="single-profile-contact">
                            <h3>Contact Info</h3>
                            <ul>
                                <li>
                                    <i class="icofont-ui-call"></i>
                                    <a href="tel:+07554332322">Call : +07 554 332 322</a>
                                </li>
                                <li>
                                    <i class="icofont-email"></i>
                                    <a href="mailto:hello@gable.com">hello@gable.com</a>
                                </li>
                                <li>
                                    <i class="icofont-location-pin"></i>
                                    4th Floor, 408 No Chamber
                                </li>
                            </ul>
                        </div>
                        <div class="single-profile-social">
                            <h3>Social Links</h3>
                            <ul>
                                <li>
                                    <i class="icofont-facebook"></i>
                                    <a href="https://www.facebook.com/" target="_blank">https://www.facebook.com</a>
                                </li>
                                <li>
                                    <i class="icofont-instagram"></i>
                                    <a href="https://www.instagram.com/" target="_blank">https://www.instagram.com</a>
                                </li>
                                <li>
                                    <i class="icofont-linkedin"></i>
                                    <a href="https://www.linkedin.com/" target="_blank">https://www.linkedin.com</a>
                                </li>
                                <li>
                                    <i class="icofont-twitter"></i>
                                    <a href="https://www.twitter.com/" target="_blank">https://www.twitter.com</a>
                                </li>
                            </ul>
                        </div>
                        <div class="single-profile-skills">
                            <h3>My Skills</h3>
                            <div class="skill">
                                <p>Frontend Design</p>
                                <div class="skill-bar skill1 wow slideInLeft animated">
                                    <span class="skill-count1">70%</span>
                                </div>
                            </div>
                            <div class="skill">
                                <p>Software Development</p>
                                <div class="skill-bar skill1 skill2 wow slideInLeft animated">
                                    <span class="skill-count1">90%</span>
                                </div>
                            </div>
                            <div class="skill">
                                <p>UIUX Design</p>
                                <div class="skill-bar skill1 skill3 wow slideInLeft animated">
                                    <span class="skill-count1">75%</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-7">
                <div class="single-profile-item">
                    <div class="single-profile-right">
                        <div class="single-profile-name">
                            <h2>Jac Jacson</h2>
                            <span>Web Consultant</span>
                            <p>Bachelor of Business Administation university of Gable</p>
                            <a href="#">
                                View CV
                                <i class="icofont-eye-alt"></i>
                            </a>
                            <a href="#">
                                Download CV
                                <i class="icofont-download"></i>
                            </a>
                        </div>
                        <div class="single-profile-textarea">
                            <div class="single-profile-heading">
                                <span></span>
                                <h3>Description</h3>
                            </div>
                            <div class="single-profile-paragraph">
                                <p class="single-profile-p">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis.Lorem ipsum dolor sit amet, consectetur adipiscing.</p>
                                <p>Risus commodo viverra maecenas accumsan lacus vel facilisis.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.</p>
                            </div>
                            <div class="single-profile-heading">
                                <span></span>
                                <h3>Education</h3>
                            </div>
                            <div class="single-profile-paragraph">
                                <ul>
                                    <li>PHD degree in Criminal Law at University of Gable Internatinal (2006)</li>
                                    <li>Master of Family Law  at University of Gable International  (2002)</li>
                                    <li>MBBS LLB (Hon’s) in  at University of Gable International (2002)</li>
                                    <li>Higher Secondary Certificate at Gable International collage  (1991)</li>
                                </ul>
                            </div>
                            <div class="single-profile-heading">
                                <span></span>
                                <h3>Research</h3>
                            </div>
                            <div class="single-profile-paragraph">
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra</p>
                            </div>
                            <div class="single-profile-heading">
                                <span></span>
                                <h3>Work Experiences</h3>
                            </div>
                            <div class="single-profile-paragraph">
                                <ul>
                                    <li>Hand On experience with Wordpress</li>
                                    <li> Better knowledge of front-end technologies, including HTML5, CSS3, JavaScript, jQuery</li>
                                    <li>Belief – believing in yourself and those around you</li>
                                    <li>Experience designing and developing responsive design websites</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Candidate Details -->

PortalForRetiredExperienced/Views/Shared/CandidateList.cshtml
@model IEnumerable<PortalForRetiredExperienced.Models.CandidateListModel>

@{
    ViewData["Title"] = "CandidateList";
}

<section class="profile-area profile-area-two pt-100">
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-sm-6 col-lg-3">
                    <div class="profile-item wow fadeInUp" data-wow-delay=".3s">
                        <img src="~/Design/img/MyProfile.jpg" alt="Profile">
                        <div class="profile-inner">
                            <h3>
                                @Html.DisplayFor(modelItem => item.CandidateName)
                            </h3>
                            <span>Business Consultant</span>
                            <h3>
                                @Html.DisplayFor(modelItem => item.Profession)
                            </h3>
                            <a href="candidate-details.html">
                                <h3>
                                    @Html.DisplayFor(modelItem => item.ProfileLink)
                                </h3>
                            </a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>

PortalForRetiredExperienced/Views/Shared/_HeaderBarPartial.cshtml
<div class="main-nav">
    <div class="container">
        <nav class="navbar navbar-expand-md navbar-light">
            <a class="navbar-brand" href="#">
                <img src="~/Design/Logo.png" alt="Logo">
            </a>
            <div class="collapse navbar-collapse mean-menu" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a  asp-controller="Home" asp-action="Index">Home </a>
                    </li>
                    <li class="nav-item">
                        <a asp-action="JobList" asp-controller="JobList" class="nav-link">Job List</a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link dropdown-toggle">Candidates <i class="icofont-simple-down"></i></a>
                        <ul class="dropdown-menu">
                            <li class="nav-item">
                                <a asp-action="CandidateList" asp-controller="CandidateList" class="nav-link">Candidate List</a>
                            </li>
                            <li class="nav-item">
                                <a asp-action="CandidateDetails" asp-controller="Candidates" class="nav-link">Candidate Details</a>
                            </li>
                            
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a asp-action="CompanyList" asp-controller="Company" class="nav-link">Company List</a>
                    </li>
                    <li class="nav-item">
                        <a asp-action="Contact"asp-controller="Contacts" class="nav-link">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a asp-action="Profile"asp-controller="Profiles" class="nav-link">Profile</a>
                    </li>
                </ul>
                <div class="common-btn">
                    <a class="login-btn" a asp-area="Identity" asp-page="/Account/Register">
                        <i class="icofont-plus-square"></i>
                        Sign Up
                    </a>
                    <a class="sign-up-btn" a asp-area="Identity" asp-page="/Account/Login">
                        <i class="icofont-user-alt-4"></i>
                        Login
                    </a>
                </div>
            </div>
        </nav>
    </div>
</div>

PortalForRetiredExperienced/Views/Shared/_JobCategoryPartial.cshtml
<section class="category-area ptb-100">
    <div class="container">
        <div class="section-title">
            <h2>Choose Your Desire Category</h2>
        </div>
        <div class="row">
            <div class="col-sm-3 col-lg-3 category-border">
                <div class="category-item">
                    <i class="flaticon-settings"></i>
                    <a href="#">Technical Support</a>
                </div>
            </div>
        </div>
    </div>
</section>

PortalForRetiredExperienced/Views/Shared/_RecentJobPartial.cshtml
<section class="job-area pb-100">
    <div class="container">
        <div class="section-title">
            <h2>Recent Jobs</h2>
        </div>
        <div class="sorting-menu">
            <ul>
                <li class="filter active" data-filter="all">All</li>
                <li class="filter" data-filter=".web">New</li>
                <li class="filter" data-filter=".ui">Featured</li>
                <li class="filter" data-filter=".branding">Recent</li>
                <li class="filter" data-filter=".ux">Full Time</li>
                <li class="filter" data-filter=".wp">Part Time</li>
            </ul>
        </div>
    </div>
</section>